version: '3.1'

services:
  db:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/resources/db/migration:/docker-entrypoint-initdb.d