version: '3.1'

services:
  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/resources/db/migration:/docker-entrypoint-initdb.d
  bank-service:
    depends_on:
      - mysql
    image: bank-service:latest
    environment:
      - "PORT=8080"
      - "GCP_SQL_ENABLED=false"
      - "DB_MYSQL_URL=jdbc:mysql://localhost/bank?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false"
      - "DB_MYSQL_USERNAME=root"
      - "DB_MYSQL_PASSWORD=root"
    ports:
      - "8080:8080"