spring:
  datasource:
    url: jdbc:mysql://localhost/bank?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    context-path: /bank
logging:
  level:
    org:
      hibernate:
        type: TRACE