spring:
  cloud:
    gcp:
      sql:
        enabled: ${GCP_SQL_ENABLED}
        database-name: ${DB_MYSQL_NAME}
        instance-connection-name: ${DB_MYSQL_INSTANCE_CONNECTION_NAME}
  datasource:
    url: ${DB_MYSQL_URL}
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: ${PORT}
