spring:
  datasource:
    url: jdbc:mysql://localhost/bank?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: ${DB_MYSQL_USERNAME}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  servlet:
    context-path: /bank
